# --- MAAC specific parameters ---

action_selector: "multinomial"
epsilon_start: .5
epsilon_finish: .01
epsilon_anneal_time: 100000
mask_before_softmax: False

runner: "parallel"
mac: "maac_mac"

buffer_size: 10000
batch_size_run: 12
batch_size: 16

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval: 200

lr: 0.0005
critic_lr: 0.0005
td_lambda: 0.8

# use MAAC
agent_output_type: "pi_logits"
learner: "maac_learner"
attend_heads: 4
norm_in: True
critic_hidden_dim: 128
critic_q_fn: "maac"
critic_baseline_fn: "maac"
critic_train_mode: "seq"
critic_train_reps: 4
gamma: 0.99
tau: 0.001
reward_scale: 100
soft: True

t_max: 5000000

name: "maac"
